name = "a0b_playstation2_controller_async"
description = "A0B PlayStation2 controller (asynchronous neutral layer)"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"

project-files=["gnat/a0b_playstation2_controller_async.gpr"]

tags=["embedded", "playstation2", "ps2"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
